import { useState } from 'react';
import { Copy, Plus, Search, Settings } from 'lucide-react';
import { ApprovalCard, Badge, Button, Callout, CheckRow, CommandBar, CommandPalette, CompactedChip, ConnectGatewayWizard, ContextInspector, Dialog, DocRow, DropZone, EmptyState, ErrorState, GatewayStatus, IconButton, Input, Kbd, ModelRoutePicker, NectarMeter, NotesList, ProceduralFly, ProfileForm, Progress, ProgressRing, ResultCard, Segmented, Select, Sheet, Skeleton, Slider, SourceChip, StatusChip, Tabs, Textarea, Toggle, Tooltip, ToastProvider, useToast, VaultPanel, Field, SENS_COPY, type DocView, type RouteView, type ProfileFieldView, type InspectorData, type SessionState, initialSession, Timeline } from '@fruitfly/ui';

const docs: DocView[] = [
  { id: '1', title: 'Lease-2025.pdf', mime: 'application/pdf', bytes: 482_000, sensitivity: 'local-only', status: 'ready', lastUsedAt: Date.now() - 600_000, chunkCount: 10 },
  { id: '2', title: 'Invoices-Q3.csv', mime: 'text/csv', bytes: 4_300, sensitivity: 'personal', status: 'embedding', progress: 0.55, chunkCount: 0 },
  { id: '3', title: 'Scan-0042.png', mime: 'image/png', bytes: 2_100_000, sensitivity: 'personal', status: 'needs_ocr', chunkCount: 0 },
  { id: '4', title: 'Notes.md', mime: 'text/markdown', bytes: 900, sensitivity: 'public', status: 'error', error: 'Could not read', chunkCount: 0 },
];
const routes = (h: RouteView['health']): RouteView[] => [
  { id: 'a', label: 'Free pool · smart', kind: 'remote', allowsPersonal: false, health: h, p50ms: 820, budgetLeft: 0.72, lastError: h === 'healthy' ? undefined : 'rate limit' },
  { id: 'b', label: 'Free pool · auto', kind: 'remote', allowsPersonal: true, health: 'healthy', p50ms: 640, budgetLeft: 0.9 },
  { id: 'c', label: 'llama3.1:8b', kind: 'local', allowsPersonal: true, health: 'healthy', p50ms: 1900 },
];
const inspector: InspectorData = { window: 32000, used: 14200, reserve: 4480, compactAt: 22400, cachedPrefixTokens: 1900, cacheHitRatio: 0.62, segments: [
  { kind: 'system', tokens: 780, fraction: 0.024, cacheable: true, sensitivity: 'public', trimmable: false, description: 'Rules, safety and style. Fixed.' }, { kind: 'tools', tokens: 960, fraction: 0.03, cacheable: true, sensitivity: 'public', trimmable: false, description: 'Tool schemas for the active groups. Fixed.' },
  { kind: 'profile', tokens: 210, fraction: 0.007, cacheable: true, sensitivity: 'personal', trimmable: false, description: 'About you digest and standing instructions.' }, { kind: 'scratchpad', tokens: 520, fraction: 0.016, cacheable: false, sensitivity: 'public', trimmable: false, description: 'Goal, findings, rejected options. Never summarised.' },
  { kind: 'docs', tokens: 3400, fraction: 0.106, cacheable: false, sensitivity: 'personal', trimmable: true, description: 'Passages retrieved from Pantry.' }, { kind: 'history', tokens: 5900, fraction: 0.184, cacheable: false, sensitivity: 'public', trimmable: true, description: 'Earlier steps, masked or summarised when long.' },
  { kind: 'observation', tokens: 2430, fraction: 0.076, cacheable: false, sensitivity: 'public', trimmable: true, description: 'The newest page or tool result.' }, { kind: 'reserve', tokens: 4480, fraction: 0.14, cacheable: false, sensitivity: 'public', trimmable: false, description: 'Room kept free for the answer.' }] };
const fields: ProfileFieldView[] = [{ key: 'full_name', label: 'Name', value: 'Asha Rao', sensitivity: 'personal', includeInDigest: true, group: 'Basics' }, { key: 'currency', label: 'Preferred currency', value: 'INR', sensitivity: 'public', includeInDigest: true, group: 'Basics' }, { key: 'standing_instructions', label: 'Standing instructions', value: 'Prefer free delivery.\nAsk before spending over ₹10,000.', sensitivity: 'personal', includeInDigest: false }];
const sess: SessionState = { ...initialSession(), status: 'working', goal: 'Find the cheapest laptop under ₹60,000', steps: [
  { id: 's1', index: 1, title: 'Opening cartwheel.example', kind: 'navigate', tool: 'navigate', state: 'done', digest: 'Opened cartwheel.example', ms: 640, tokens: 90, startedAt: 0 },
  { id: 's2', index: 2, title: 'Typing into "Search products"', kind: 'type', tool: 'type', state: 'failed', digest: 'Typing failed', unexpected: 'Something is in the way of that button.', ms: 210, startedAt: 0 },
  { id: 's3', index: 3, title: 'Clicking "Necessary only"', kind: 'click', tool: 'click', state: 'done', digest: 'Clicked "Necessary only"', ms: 380, startedAt: 0 },
  { id: 's4', index: 4, title: 'Asking helpers', kind: 'search', tool: 'delegate', state: 'active', startedAt: 0 }], compactions: [{ why: 'threshold', stepsMasked: 14, turnsSummarized: 0, tokensBefore: 24100, tokensAfter: 9800, atStep: 3 }],
  subagents: [{ id: 'r1', kind: 'researcher', label: 'Looking up bazaar.example', phase: 'start' }, { id: 'r2', kind: 'researcher', label: 'Looking up gizmo-depot.example', phase: 'done', summary: 'Acer Aspire 5 at ₹46,999' }] };

function Toasts() { const t = useToast(); return <Button onClick={() => t.push({ text: 'Added to your Pantry', action: { label: 'Undo', run: () => {} } })}>Show a toast</Button>; }

export function ComponentsPage() {
  const [on, setOn] = useState(true); const [tab, setTab] = useState<'a' | 'b'>('a'); const [dlg, setDlg] = useState(false); const [sheet, setSheet] = useState(false); const [pal, setPal] = useState(false);
  const [sens, setSens] = useState<'public' | 'personal' | 'local-only'>('personal'); const [vol, setVol] = useState(40); const [sel, setSel] = useState('smart');
  const [vault, setVault] = useState<'unset' | 'locked' | 'unlocked'>('unset');
  return (
    <ToastProvider>
      <h2>Buttons & inputs</h2>
      <div className="sect"><div className="row"><Button variant="primary" arrow>Primary</Button><Button>Secondary</Button><Button variant="ghost">Ghost</Button><Button variant="danger">Danger</Button><Button variant="primary" loading>Loading</Button><Button disabled>Disabled</Button><Button size="sm" icon={<Plus />}>Small</Button><Button variant="primary" size="lg">Large</Button><IconButton label="Settings"><Settings /></IconButton><IconButton label="Copy" aria-pressed><Copy /></IconButton><Kbd>⌘K</Kbd></div>
        <div className="two"><Field label="Name" hint="As you like it">{(id) => <Input id={id} placeholder="Asha" />}</Field><Field label="Email" error="That doesn't look like an email.">{(id) => <Input id={id} defaultValue="asha@" />}</Field><Field label="Notes">{(id) => <Textarea id={id} rows={3} placeholder="Anything" />}</Field>
          <div className="ff-stack"><Select label="Route" value={sel} onChange={setSel} options={[{ value: 'fast', label: 'Fast' }, { value: 'smart', label: 'Smart' }]} /><div className="ff-row"><Toggle label="Demo" checked={on} onChange={setOn} /> <span>Toggle</span></div><Slider label="Cap" min={0} max={100} value={vol} onChange={setVol} /><Segmented label="Sensitivity" value={sens} onChange={setSens} options={[{ value: 'public', label: 'Public' }, { value: 'personal', label: 'Personal' }, { value: 'local-only', label: 'Local-only' }]} /><span className="ff-hint">{SENS_COPY[sens]}</span></div></div></div>
      <h2>Status, progress, badges</h2>
      <div className="sect"><div className="row">{(['idle', 'working', 'paused', 'needs_you', 'throttled', 'done', 'failed', 'stopped'] as const).map((s) => <StatusChip key={s} status={s} throttleUntil={Date.now() + 12000} />)}</div>
        <div className="row"><Badge>Neutral</Badge><Badge tone="honey">Honey</Badge><Badge tone="lime">Lime</Badge><Badge tone="plum">Plum</Badge><Badge tone="danger">Danger</Badge><NectarMeter fraction={0.72} usage={{ tokensUsed: 42000, tokensCap: 250000, stepsUsed: 7, stepsCap: 40, cacheRead: 18000 }} /><NectarMeter fraction={0.12} /><ProgressRing value={0.6} label="Demo" /><div style={{ width: 160 }}><Progress value={0.45} label="Demo" /></div><Skeleton w={120} /><Tooltip label="A short tip"><Button size="sm">Hover me</Button></Tooltip></div></div>
      <h2>Tabs, overlays, toasts</h2>
      <div className="sect"><Tabs label="Demo" value={tab} onChange={setTab} tabs={[{ value: 'a', label: 'Task' }, { value: 'b', label: 'Pantry' }]} /><div className="row"><Button onClick={() => setDlg(true)}>Dialog</Button><Button onClick={() => setSheet(true)}>Sheet</Button><Button onClick={() => setPal(true)} icon={<Search />}>Palette</Button><Toasts /></div></div>
      <Dialog open={dlg} onClose={() => setDlg(false)} title="Delete everything?" description="This removes your documents, profile, notes and vault from this device."><Field label="Type DELETE to confirm">{(id) => <Input id={id} />}</Field><div className="ff-actions" style={{ marginTop: 14 }}><Button onClick={() => setDlg(false)}>Cancel</Button><Button variant="danger-solid">Delete everything</Button></div></Dialog>
      <Sheet open={sheet} onClose={() => setSheet(false)} title="Sheet"><b>A bottom sheet</b><p className="ff-muted">Used for touch and narrow layouts.</p><Button onClick={() => setSheet(false)}>Close</Button></Sheet>
      <CommandPalette open={pal} onClose={() => setPal(false)} items={[{ id: 'a', label: 'New task', hint: '/new', run: () => {} }, { id: 'b', label: 'Open Pantry', run: () => {} }]} />
      <h2>Agent surface</h2>
      <div className="two"><div className="sect"><Timeline session={sess} /><CompactedChip report={{ why: 'user', stepsMasked: 5, turnsSummarized: 2, tokensBefore: 9000, tokensAfter: 4000 }} /></div>
        <div className="sect"><ApprovalCard approval={{ id: 'a', taskId: 't', action: 'Clicking "Pay ₹2,210"', reason: 'This will place an order or take payment.', level: 'sensitive', site: 'northbank.example', preview: [{ label: 'Target', value: 'Pay ₹2,210' }, { label: 'From', value: 'Savings ••4821' }] }} onApprove={() => {}} onCancel={() => {}} onTakeover={() => {}} /></div></div>
      <div className="two" style={{ marginTop: 16 }}><div className="sect"><ResultCard revealed result={{ title: 'Redmi Book 15 is the cheapest under ₹60,000', summary: 'The lowest price I found is ₹42,990 at Bazaar. If you want a Core i5 with 16 GB, the Acer Aspire 5 is ₹46,999 at Gizmo Depot.', table: { columns: ['Shop', 'Laptop', 'Price'], rows: [['Bazaar', 'Redmi Book 15', '₹42,990'], ['Cartwheel', 'Lenovo IdeaPad Slim 3', '₹44,990'], ['Gizmo Depot', 'Acer Aspire 5', '₹46,999']] }, verification: 'Checked against 3 sources', sources: [{ kind: 'page', title: 'Bazaar', url: 'https://bazaar.example/' }, { kind: 'pantry', title: 'Lease-2025', page: 3 }], status: 'success' }} onFresh={() => {}} onSave={() => {}} onReplay={() => {}} /></div>
        <div className="sect"><ContextInspector data={inspector} onCompact={() => {}} onFresh={() => {}} /></div></div>
      <div className="sect" style={{ marginTop: 16 }}><CommandBar busy={false} onSubmit={() => {}} onSlash={() => {}} onStop={() => {}} suggestions={['Find the cheapest laptop under ₹60,000', 'Cheapest flight to Paris']} onAttach={() => {}} /></div>
      <h2>Pantry</h2>
      <div className="two"><div className="sect">{docs.map((d) => <DocRow key={d.id} doc={d} onSensitivity={() => {}} onRemove={() => {}} />)}<DropZone onFiles={() => {}} onPaste={() => {}} /></div><div className="sect"><ProfileForm fields={fields} digestTokens={210} standing={{ lines: 2, tokens: 14, overLimit: false }} onChange={() => {}} /><NotesList notes={[{ id: 'n1', text: 'Prefers aisle seats', status: 'proposed' }, { id: 'n2', text: 'Vegetarian meals', status: 'kept' }]} onKeep={() => {}} onDelete={() => {}} onEdit={() => {}} /></div></div>
      <div className="two" style={{ marginTop: 16 }}>{(['unset', 'locked', 'unlocked'] as const).map((s) => <VaultPanel key={s} state={s === 'unset' ? vault : s} fields={[{ key: 'passport', label: 'Passport', requiresApproval: true }]} onSetup={() => setVault('unlocked')} onUnlock={() => {}} onLock={() => {}} onAdd={() => {}} onRemove={() => {}} />)}</div>
      <h2>Models & gateway</h2>
      <div className="two"><div className="sect"><div className="row"><GatewayStatus state="connected" /><GatewayStatus state="asleep" /><GatewayStatus state="auth" /><GatewayStatus state="none" /></div><ModelRoutePicker profiles={{ fast: routes('healthy'), smart: routes('limited'), vision: [], embed: routes('healthy').slice(2), local: routes('healthy').slice(2) }} onReorder={() => {}} onTogglePersonal={() => {}} /></div>
        <div className="sect"><ConnectGatewayWizard onDone={() => {}} api={{ detect: async () => ({ reachable: true, authRequired: true }), test: async () => ({ chat: true, tools: true, stream: true }), save: async () => {} }} /></div></div>
      <h2>Empty, error, callouts</h2>
      <div className="two"><div className="sect"><EmptyState art={<ProceduralFly size={64} mood="sleeping" label="" followCursor={false} />} title="Nothing here yet." body="Add a document and I'll know it." /></div><div className="sect"><ErrorState title="That key didn't work." body="Reconnect the gateway to carry on." action={<Button size="sm" variant="primary">Reconnect</Button>} /><Callout tone="warn" title="Pantry is nearly full.">Manage storage to keep indexing.</Callout><Callout tone="info" title="Tip">Press <Kbd>/</Kbd> for commands.</Callout><CheckRow state="ok">Answers a question</CheckRow><CheckRow state="fail">Can use tools</CheckRow><SourceChip source={{ kind: 'pantry', title: 'Lease-2025', page: 3 }} /></div></div>
    </ToastProvider>
  );
}
